### PR TITLE
Set edit uri for main branch

### PR DESCRIPTION
**Pull request by prattmic**
This does not default to branch main according to the mkdoc docs [1]. Set it based on the documented GitHub default, swapped for main.

[1] https://www.mkdocs.org/user-guide/configuration/

### CODE REVIEW

**Comment by prattmic** [comment]
Fair warning, I wrote this on my phone, so it is untested :)

**Comment by prattmic** [comment]
Oh fooey, I forgot to add the fixes line and now I think I need to wait to get to a real computer to adjust.

**Comment by prattmic** [comment]
Fixes #106

**Review by dominichamon — APPROVED** [review]

**Comment by dominichamon** [comment]
thank you again :)

**Pull request merged**
