### PR TITLE
api best practice rename

### PR DESCRIPTION
**Pull request by dmah42**
these are all suggestions from the proto best practices guide.

tl;dr:

1. suffix packages with versions
2. suffix services with "Service"
3. prefix request/response with service names
4. include `_UNSPECIFIED` enum entries for value 0

### CODE REVIEW

**Comment by future-highway** [comment]
The scripts in the examples dir are broken, but let's see how we like these changes anyway.

**Comment by future-highway** [comment]
@cla-bot check

**Review by krisnova — APPROVED** [review]

**Comment by krisnova** [comment]
@cla-bot check

**Comment by dmah42** [comment]
@cla-bot check

**Review by krisnova — APPROVED** [review]

**Pull request merged**
