### PR TITLE
upgrade buf installer to 1.28.1

### PR DESCRIPTION
**Pull request by dmah42**

### CODE REVIEW

**Comment by dmah42** [comment]
hm.  local tests are failing due to a `socket2::Socket` issue which comes from the deno_net dependency.  i may need to bump the deno dependencies to be able to run anything locally (or wait for #491)

**Review by jesse-peters — APPROVED** [review]

**Comment by jesse-peters** [comment]
Looks good other than that failing test

**Comment by dmah42** [comment]
> Looks good other than that failing test

dunno why that Tester (101) keeps skipping.

**Comment by dmah42** [comment]
"LLVM ERROR: IO failure on output stream: No space left on device
error: could not compile `swc_common` (lib)
warning: build failed, waiting for other jobs to finish...
LLVM ERROR: IO failure on output stream: No space left on device
error: could not compile `deno_core` (lib)
error: couldn't create a temp dir: No space left on device (os error 28) at path "/__w/aurae/aurae/target/debug/deps/rmetatjWHvq"
error: could not compile `h2` (lib) due to previous error"

not really sure we can do much about this :/

**Pull request merged**
