### PR TITLE
Update license automation

### LINKED ISSUE #468: SPDX License Identifiers in the Source Code
Folks might consider vendoring small crates and modules from the Aurae source code.

Can we please add SPDX license identifiers **to every .rs file in the project**?

For more on using the SPDX in source code read [the SPDX tutorial](https://github.com/david-a-wheeler/spdx-tutorial/blob/master/README.md#spdx-license-expressions-in-source-code-files).

Basically I think we just need to use this and fill in the blanks in each of our headers.

```
# Copyright [year file created] - [last year file modified], [project founder] and the [project name] contributors
# SPDX-License-Identifier: [SPDX license expression]
```

### PR DESCRIPTION
**Pull request by bpmooch**
Update automation scripts for adding license headers to files. Also shortens the length of the headers to take up less lines in each file.

Moving forward, when you add new files, simply run `make headers` before submitting your pull request. You can also manually run `DRY_RUN=1 ./hack/headers-write` from the root of the repo to get a list of the changes that `make headers` is going to perform

closes #468

### CODE REVIEW

**Comment by bpmooch** [comment]
@dmah42 do me a favor and don't add a merge commit if the need comes up

**Review by dmah42 — APPROVED** [review]

**Comment by dmah42** [comment]
> @dmah42 do me a favor and don't add a merge commit if the need comes up

i feel like these three commits can be merged without losing any useful information, and given they fix issues with the first commit maybe a merge is appropriate? :)

**Comment by bpmooch** [comment]
> > @dmah42 do me a favor and don't add a merge commit if the need comes up
> 
> i feel like these three commits can be merged without losing any useful information, and given they fix issues with the first commit maybe a merge is appropriate? :)

do you mean squash or merge?

**Comment by dmah42** [comment]
> > > @dmah42 do me a favor and don't add a merge commit if the need comes up
> > 
> > i feel like these three commits can be merged without losing any useful information, and given they fix issues with the first commit maybe a merge is appropriate? :)
> 
> do you mean squash or merge?

I don't know... whatever GitHub does... probably squash.

were you asking me not to hit the "update branch" button or not to squash on merge?

**Comment by dmah42** [comment]
I can't see what is causing the failure here.  feels like generated code is linting badly.  maybe we suppress the lint check?

**Comment by bpmooch** [comment]
> were you asking me not to hit the "update branch" button or not to squash on merge?

Is it ok to keep the small commits and rebase them over main? I am going to be removing an amount of things in my fork and doing things in small commits helps me maintain parity with upstream

If not, no worries, let's just get this merged and I'll figure it out after

**Review by dmah42 — APPROVED** [review]

**Review by dmah42 — DISMISSED** [review]

**Review by dmah42 — APPROVED** [review]

**Comment by dmah42** [comment]
i think rebasing this onto the base branch should resolve the issues.

**Comment by dmah42** [comment]
woo!

**Pull request merged**
