### PR TITLE
More refactoring of init module (mainly network)

### PR DESCRIPTION
**Pull request by future-highway**
Refactored the network code to better contain it in its own module. 

Also eliminated some errors from `init/fs`, as we currently control the input and can use `expect` instead.

Note: Network can probably be improved if the link indexes are stable across calls, but I didn't know if that is true, so did not make that assumption.

### CODE REVIEW

**Comment by krisnova** [comment]
LGTM but leaving for @Vincinator to merge/review

**Review by Vincinator — APPROVED** [review]
Thanks - looks good!

**Comment by future-highway** [comment]
@Vincinator thanks for the review. Resolving the conflicts removed your review for the merge. If you are still around to give it a quick approve, great. No rush though.

**Review by Vincinator — APPROVED** [review]
Hey, @future-highway - this is an easy approve. Thank you!

**Pull request merged**
