### PR TITLE
s/aurae-proto/proto/

### PR DESCRIPTION
**Pull request by dmah42**
part of #371 

simplify the view of things by removing the previx.

### CODE REVIEW

**Review by future-highway — DISMISSED** [review]
Currently weakly holding the opinion that we shouldn't make this change. But, looking from my phone, I don't see any issues. Once again, I'll leave it you dma if you want a different review as well.

**Comment by dmah42** [comment]
gonna escalate this to @krisnova for BDFL approval.

**Comment by krisnova** [comment]
Curious why @future-highway thinks we shouldn't rename the directory? 

I have a weakly held opinion that we should try not to use the name of the project in nested folder names, but if there is a good reason for it such as "This is the main Aurae API" I am actually okay with it.

**Comment by dmah42** [comment]
proto is not the main API (that's in api) but if we ever publish aurae-proto or aurae-client as crates, we'd want the prefix in there.

i assume we can publish a crate called "aurae-foo" from a directory called "foo" but i don't know for sure.

**Comment by future-highway** [comment]
By convention, the crate name would match the directory name but  I don't believe there is a technical requirement at any point, including publishing a crate. I think it's ok to rename if that is the preference.

**Comment by dmah42** [comment]
ready to merge :)

**Review by future-highway — APPROVED** [review]
LGTM

**Comment by krisnova** [comment]
Looked at this on the stream and I think we are okay with have packages names `foo` that are published to crates.io as `aurae-foo`.

Additionally we now have control [crates.io/crates/aurae](https://crates.io/crates/aurae) which maybe is where we want to publish crates such as the client? 

I am wondering under what conditions a developer would try:

```bash 
cargo add aurae
```

and I think maybe the expectation is to get the rust client? although we can make that decision later! 

Hope this helps explain my reasoning. Basically I am convinced we will likely be renaming/mapping these directories to other crate names (and maybe even repos?) in the future.

**Pull request merged**
