### PR TITLE
Simplify `Cells` by moving lock to `CellService`

### PR DESCRIPTION
**Pull request by future-highway**
This should also make it a bit more straight forward for creating grpc `Response`s for cells.

### CODE REVIEW

**Review by dmah42 — COMMENTED** [review]
any chance the tests can come back?

**Comment by future-highway** [comment]
> any chance the tests can come back?

maybe, I'll check

**Comment by future-highway** [comment]
Ok, updated tests are back. Please see the TODO note in `impl Drop for Cells`. I used `Drop` to cleanup the groups that are created when the tests run.

**Comment by future-highway** [comment]
Ok, the tests that can't be run in GH can now be marked with #[ignore]. `make test` will still run them, but `make testci` will not (neither will `cargo test`). We also have a `make prcheck` which is intended to mimic what GH checks, and that will run all tests (`make test`).

**Review by dmah42 — APPROVED** [review]

**Pull request merged**
