### PR TITLE
Updates related to advisories

### PR DESCRIPTION
**Pull request by future-highway**
I was only able to eliminate the warning advisory for now.

### CODE REVIEW

**Comment by future-highway** [comment]
Tester 101 is failing because it is timing out. Do we want to extend past 30 minutes until we find other solutions?

**Comment by dmah42** [comment]
if our tests are taking >30 minutes then i think we've done something wrong :/

of course we can extend it but how far is too far?

**Comment by future-highway** [comment]
I was hoping we could use cargo-chef in the docker file to speed up 101, but it wasn't effective (dependency crate builds were not being cached).

**Comment by future-highway** [comment]
@cla-bot check

**Comment by future-highway** [comment]
@cla-bot check

**Comment by krisnova** [comment]
@cla-bot check

**Comment by krisnova** [comment]
@cla-bot check

**Comment by krisnova** [comment]
Fixed it :) 

Thanks @Preskton

**Pull request merged**
