### PR TITLE
WIP: Removes copyright years from header

### PR DESCRIPTION
**Pull request by jesse-peters**
This PR is in response to a conversation in discord today with @krisnova. The code copyright headers aren't strictly required. Changing the version number annually will grow in scope and create work that doesn't need to be done.

This removes the year range from the headers. 

There will be additional PRs to 
- add a GHA workflow to check if they are valid across the project.
- these will be consistent across projects, and documented in the contributions.md once the process is defined

### CODE REVIEW

**Comment by jesse-peters** [comment]
I want to audit the header scripts in the `hack` directory before this is ready for a review.

**Comment by dmah42** [comment]
we also need to add a NOTICE file if we do this as that contains the copyright: https://infra.apache.org/apply-license.html#new

**Comment by krisnova** [comment]
Do we update this PR or open a new one?

**Comment by jesse-peters** [comment]
Sorry, family was sick all week so lost track of this. I'll reopen a new one thats cleaner

**Pull request closed without merging**
